### ISSUE TITLE
Support for ILifetimeScope in addition to Container

### ISSUE THREAD

**Issue by RwSgxx** [fluentassertions/fluentassertions.autofac#27]
The single way provided by Autofac to add new components after the container is built is by creating a new LifeTimeScope. 
-> The use case is: build the container -> BeginLifetimeScope + additional registration -> test if the new registrations are in the new LifetimeScope.

**Comment by mkoertgen** [comment]
Hi @RwSgxx , thanks for reaching out. Can you provide an idiomatic example on how the Api should look like? 

If i understand correctly, your suggestion is adding/moving the already existing assertions from `IContainer` down to `ILifeTimeScope` so that something like this would be possible:

```csharp
var myInstance = Substitute.For<IDisposable>();
using var scope = container.BeginLifetimeScope(builder => builder
    .RegisterInstance(myInstance).As<IDisposable>());
scope.Should().Resolve<IDisposable>().As<IDisposable>();
```

Sounds good!

**Comment by mkoertgen** [comment]
Closed due to inactivity.
